# Generated by Django 5.2.7 on 2025-10-18 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cand', '0001_initial'),
        ('swe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title (e.g., Backend Engineer)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Role description and responsibilities')),
                ('num_rounds', models.PositiveIntegerField(default=3, help_text='Number of interview rounds for this role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_swe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to='swe.swe')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='Round number (1, 2, 3, etc.)')),
                ('name', models.CharField(help_text='Round name (e.g., Coding Challenge)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the round')),
                ('difficulty_level', models.CharField(choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], default='easy', max_length=10)),
                ('data_structures', models.TextField(blank=True, help_text='Comma-separated list of topics')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Time limit in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='interview.role')),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
                'ordering': ['round_number'],
                'unique_together': {('role', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='Interview score as percentage (0-100)')),
                ('notes', models.TextField(blank=True, help_text='Interview notes and feedback')),
                ('screen_video', models.URLField(blank=True, help_text='URL to screen recording video', max_length=500)),
                ('candidate_video', models.URLField(blank=True, help_text='URL to candidate video recording', max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='cand.candidate')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interview.round')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
