# Generated by Django 5.2.7 on 2025-10-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='success_metrics',
            field=models.TextField(blank=True, help_text='Metrics set by SWE for each round'),
        ),
    ]
