# Generated by Django 5.2.7 on 2025-10-19 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_round_success_metrics'),
        ('recruit', '0005_remove_round_role_alter_round_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='owning_recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owning_recruiter', to='recruit.recruiter'),
        ),
    ]
