# Generated by Django 5.2.7 on 2025-10-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_role_owning_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
