# Generated by Django 5.2.7 on 2025-10-19 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interview_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='LeetCode title to avoid repeats', max_length=300, unique=True)),
                ('statement', models.TextField(help_text='The problem statement/description')),
                ('test_cases', models.JSONField(help_text='Test cases as JSON dict')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.round')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='question',
            field=models.ForeignKey(blank=True, help_text='The specific question asked in this interview', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='interview.question'),
        ),
    ]
