# Generated by Django 5.2.7 on 2025-10-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_question_interview_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='time_limit',
            field=models.PositiveIntegerField(default=3, help_text='Time limit in minutes'),
        ),
    ]
