# Generated by Django 5.2.7 on 2025-10-18 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title (e.g., Backend Engineer)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Role description and responsibilities')),
                ('num_rounds', models.PositiveIntegerField(default=3, help_text='Number of interview rounds for this role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('current_round', models.PositiveIntegerField(default=1, help_text='Current round number')),
                ('ai_score', models.FloatField(default=0.0, help_text='AI evaluation score (0-1)')),
                ('notes', models.TextField(blank=True)),
                ('needs_review', models.BooleanField(default=False, help_text='Requires manual SWE review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruit.role')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='Round number (1, 2, 3, etc.)')),
                ('name', models.CharField(help_text='Round name (e.g., Coding Challenge)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the round')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('data_structures', models.TextField(blank=True, help_text='Comma-separated list of topics')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Time limit in minutes')),
                ('max_score', models.PositiveIntegerField(default=100, help_text='Maximum score for this round')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='recruit.role')),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
                'ordering': ['round_number'],
                'unique_together': {('role', 'round_number')},
            },
        ),
    ]
