# Generated by Django 5.2.7 on 2025-10-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_alter_round_difficulty_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='max_score',
        ),
    ]
