# Generated by Django 5.2.7 on 2025-10-19 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_remove_round_max_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['round_number']},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ai_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='num_rounds',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='round',
            name='data_structures',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='time_limit',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
