# Generated by Django 5.2.7 on 2025-10-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_alter_candidate_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
